version: '3'
services:

  # The Application
  app:
    image: kadza/laravel-app
    working_dir: /var/www
    env_file: '.env'
    volumes:
      - ./:/var/www
    environment:
      - "DB_HOST=database"

  # The Web Server
  web:
    image: kadza/laravel-web
    volumes:
      - "${LE_DIR}:/etc/letsencrypt"
    ports:
      - 80:80
      - 443:443

  # The Database
  database:
    image: mysql:latest
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata: